### PR TITLE
fix 1.21.3 startup

### PR DESCRIPTION
**Pull request by CrazyDev05**
Fixes the 1.21.3 initialization #26

### CODE REVIEW

**Comment by SkytAsul** [comment]
This won't work for mappings generation as it is done completely offline, without a server running. I will work that out in another manner. Thanks for the try though!

**Comment by CrazyDev05** [comment]
i tested it to work fine, it's accessing the CraftWorld::getHandle method which works just fine

**Comment by SkytAsul** [comment]
No you didn't, it crashes instantly:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.bukkit.Server.getWorlds()" because "org.bukkit.Bukkit.server" is null
	at org.bukkit.Bukkit.getWorlds(Bukkit.java:624)
	at fr.skytasul.glowingentities.GlowingEntities$Packets.loadReflection(GlowingEntities.java:443)
	at fr.skytasul.reflection.shrieker.MappingsShrieker.registerVersionMappings(MappingsShrieker.java:56)
	at fr.skytasul.glowingentities.GlowingEntitiesMappingsGenerator.start(GlowingEntitiesMappingsGenerator.java:40)
	at fr.skytasul.glowingentities.GlowingEntitiesMappingsGenerator.main(GlowingEntitiesMappingsGenerator.java:55)
```
That's pretty normal, without a server there can't be any world to fetch.

**Comment by CrazyDev05** [comment]
ahh load it after the first world loaded

**Comment by CrazyDev05** [comment]
but the fact that the constructor now needs a worlds makes that necessary anyway

**Comment by CrazyDev05** [comment]
mb for get what I said I skipped the mappings generator part

**Comment by SkytAsul** [comment]
> but the fact that the constructor now needs a worlds makes that necessary anyway

Yup but I found a better solution don't worry


> mb for get what I said I skipped the mappings generator part

That's alright, it's not something you think about at first

**Pull request closed without merging**
